<a href="https://colab.research.google.com/github/javmohir/python_darslari/blob/main/quduqlar_correlyasiya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
data={
    'yosh':[10,20,30,40,50,60],
    'yil':[2010,2000,1990,1980,1970,1960]
}
obj=pd.DataFrame(data)
obj

   yosh   yil
0    10  2010
1    20  2000
2    30  1990
3    40  1980
4    50  1970
5    60  1960

In [4]:
obj['yosh'].corr(obj['yil'])

-0.9999999999999998

In [6]:
data={
    'son':[10,20,30,40,50,60,70,80,90],
    'sum':[2010,2020,2030,2040,2050,2060,2070,2080,2090]
    }
obj1=pd.DataFrame(data)
obj1

   son   sum
0   10  2010
1   20  2020
2   30  2030
3   40  2040
4   50  2050
5   60  2060
6   70  2070
7   80  2080
8   90  2090

In [7]:
obj1['son'].corr(obj1['sum'])

0.9999999999999999

In [19]:
data={
    'quduq t/r':[154,157,158,169,312,309,383,358,363,367,4,170,171,172,173,185,313,366,370,
                 13,52,120,122,219,275,315,324],
    'q/q bosimi':[12,13,13,14,14,13,14,13.5,14.7,14.1,13,13,14,14,14,13,14,14.3,14.3,
                  10,10,10,10,10,11,11,11],
    'kunlik sarf':[149,119,90,44,129,49,105,99,71,108,119,149,166,94,150,91,77,89,85,
                   127,13,104,129,134,91,114,77],
    'soatlik sarf':[6.2,5,3.8,1.8,5.4,2,4.4,4.1,3,4.5,5,6.2,6.9,3.9,6.3,3.8,3.2,3.7,3.5,
                    5.3,0.5,4.3,5.4,5.6,3.8,4.8,3.2],
    'quvur uzunligi':[528,597,738,845,376,501,1764,1370,1993,2210,760,1190,943,643,1258,1221,441,470,857,
                      2524,1279,1215,632,900,900,1578,1450]
}
obj2=pd.DataFrame(data)
obj2

    quduq t/r  q/q bosimi  kunlik sarf  soatlik sarf  quvur uzunligi
0         154        12.0          149           6.2             528
1         157        13.0          119           5.0             597
2         158        13.0           90           3.8             738
3         169        14.0           44           1.8             845
4         312        14.0          129           5.4             376
5         309        13.0           49           2.0             501
6         383        14.0          105           4.4            1764
7         358        13.5           99           4.1            1370
8         363        14.7           71           3.0            1993
9         367        14.1          108           4.5            2210
10          4        13.0          119           5.0             760
11        170        13.0          149           6.2            1190
12        171        14.0          166           6.9             943
13        172        14.0           94           3.9             643
14        173        14.0          150           6.3            1258
15        185        13.0           91           3.8            1221
16        313        14.0           77           3.2             441
17        366        14.3           89           3.7             470
18        370        14.3           85           3.5             857
19         13        10.0          127           5.3            2524
20         52        10.0           13           0.5            1279
21        120        10.0          104           4.3            1215
22        122        10.0          129           5.4             632
23        219        10.0          134           5.6             900
24        275        11.0           91           3.8             900
25        315        11.0          114           4.8            1578
26        324        11.0           77           3.2            1450

In [20]:
obj2['q/q bosimi'].corr(obj2['kunlik sarf'])

-0.013102048710976354

In [21]:
obj2.corr()

,quduq t/r,q/q bosimi,kunlik sarf,soatlik sarf,quvur uzunligi
quduq t/r,1.000000,0.480648,-0.180810,-0.180608,0.060969
q/q bosimi,0.480648,1.000000,-0.013102,-0.012420,-0.154742
kunlik sarf,-0.180810,-0.013102,1.000000,0.999829,0.006954
soatlik sarf,-0.180608,-0.012420,0.999829,1.000000,0.009681
quvur uzunligi,0.060969,-0.154742,0.006954,0.009681,1.000000

In [22]:
obj2.corrwith(obj2['kunlik sarf'])

quduq t/r        -0.180810
q/q bosimi       -0.013102
kunlik sarf       1.000000
soatlik sarf      0.999829
quvur uzunligi    0.006954
dtype: float64

In [23]:
obj2

    quduq t/r  q/q bosimi  kunlik sarf  soatlik sarf  quvur uzunligi
0         154        12.0          149           6.2             528
1         157        13.0          119           5.0             597
2         158        13.0           90           3.8             738
3         169        14.0           44           1.8             845
4         312        14.0          129           5.4             376
5         309        13.0           49           2.0             501
6         383        14.0          105           4.4            1764
7         358        13.5           99           4.1            1370
8         363        14.7           71           3.0            1993
9         367        14.1          108           4.5            2210
10          4        13.0          119           5.0             760
11        170        13.0          149           6.2            1190
12        171        14.0          166           6.9             943
13        172        14.0           94           3.9             643
14        173        14.0          150           6.3            1258
15        185        13.0           91           3.8            1221
16        313        14.0           77           3.2             441
17        366        14.3           89           3.7             470
18        370        14.3           85           3.5             857
19         13        10.0          127           5.3            2524
20         52        10.0           13           0.5            1279
21        120        10.0          104           4.3            1215
22        122        10.0          129           5.4             632
23        219        10.0          134           5.6             900
24        275        11.0           91           3.8             900
25        315        11.0          114           4.8            1578
26        324        11.0           77           3.2            1450

In [24]:
obj2.describe()

        quduq t/r  q/q bosimi  kunlik sarf  soatlik sarf  quvur uzunligi
count   27.000000   27.000000    27.000000     27.000000       27.000000
mean   225.703704   12.662963   102.666667      4.281481     1080.851852
std    114.564666    1.636870    35.030756      1.472841      561.685903
min      4.000000   10.000000    13.000000      0.500000      376.000000
25%    157.500000   11.000000    87.000000      3.600000      637.500000
50%    185.000000   13.000000   104.000000      4.300000      900.000000
75%    319.500000   14.000000   128.000000      5.350000     1324.500000
max    383.000000   14.700000   166.000000      6.900000     2524.000000